#!/bin/bash

# detect python install
if command -v python3 &>/dev/null; then
    PYTHON="python3"
elif command -v python &>/dev/null; then
    PYTHON="python"
else
    echo "Python is not accessible with python/python3."
    exit 1
fi

$PYTHON ecc.py "./src/c.g" "$@"
